package com.github.wangfeng.iadmin.common.po.entity;

import lombok.Data;

import java.util.Date;

@Data
public class AdminSysMenuDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.id
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.name
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.left
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Long left;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.right
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Long right;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.level
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.icon
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.url
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.create_date
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.create_by
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.update_date
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.update_by
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String updateBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.status
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.permission
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin_sys_menu.p_id
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    private Long parentId;



}