package com.github.wangfeng.iadmin.common.po.entity;

import lombok.Data;

@Data
public class DemoDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.user_name
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.password
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    private String password;


}