package com.github.wangfeng.iadmin.dao;

import com.github.wangfeng.iadmin.common.po.dto.AdminSysUserRoleRelWithPageDTO;
import com.github.wangfeng.iadmin.common.po.entity.AdminSysUserDO;
import com.github.wangfeng.iadmin.common.po.entity.AdminSysUserRoleRelDO;
import java.util.List;

public interface AdminSysUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    int insert(AdminSysUserRoleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    int insertSelective(AdminSysUserRoleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    AdminSysUserRoleRelDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    int updateByPrimaryKeySelective(AdminSysUserRoleRelDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user_role_rel
     *
     * @mbg.generated Wed Sep 18 13:11:36 CST 2019
     */
    int updateByPrimaryKey(AdminSysUserRoleRelDO record);

    /**
     * 获取角色A的用户列表
     * @param adminSysUserRoleRelWithPageDTO
     * @return
     */
    List<AdminSysUserDO> selectRoleOwners(AdminSysUserRoleRelWithPageDTO adminSysUserRoleRelWithPageDTO);

}