package com.github.wangfeng.iadmin.dao;

import com.github.wangfeng.iadmin.common.po.dto.AdminSysUserQueryWithPageDTO;
import com.github.wangfeng.iadmin.common.po.entity.AdminSysUserDO;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminSysUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    int insert(AdminSysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    int insertSelective(AdminSysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    AdminSysUserDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    int updateByPrimaryKeySelective(AdminSysUserDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_user
     *
     * @mbg.generated Tue Sep 17 22:44:54 CST 2019
     */
    int updateByPrimaryKey(AdminSysUserDO record);

    List<AdminSysUserDO> selectAllWithFuzzyConditions(AdminSysUserQueryWithPageDTO adminSysUserQueryWithPageDTO);

    long countByLoginName(@Param("loginName") String loginName);

    int updateUsersStatus(List<Long> ids, int status);
}