package com.github.wangfeng.iadmin.dao;


import com.github.wangfeng.iadmin.common.po.entity.AdminSysMenuDO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface AdminSysMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_menu
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_menu
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    int insert(AdminSysMenuDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_menu
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    AdminSysMenuDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_menu
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    List<AdminSysMenuDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_sys_menu
     *
     * @mbg.generated Sun Sep 15 10:16:32 CST 2019
     */
    int updateByPrimaryKey(AdminSysMenuDO record);


    /**
     * 基于左右值得树状存储结构 right=right+2
     * @param right
     * @return
     */
    int updateRightForAddMenu(Long right);

    /**
     * 基于左右值得树状存储结构 left=left+2
     * @param right
     * @return
     */
    int updateLeftForAddMenu(Long right);

    /**
     * 查询所有子节点菜单
     * @param left
     * @param right
     * @return
     */
    List<AdminSysMenuDO> listDescendantMenus(@Param("left") Long left, @Param("right") Long right,@Param("status") Integer status);

    /**
     * 查询所有父祖节点
     * @param left
     * @param right
     * @param statusCode
     * @return
     */
    List<AdminSysMenuDO> listAncestralMenus(Long left, Long right, int statusCode);

    void deleteForRemoveMenu(@Param("left") Long left, @Param("right") Long right);

    void updateRightForRemoveMenu(@Param("width") int width, @Param("right") Long right);

    void updateLeftForRemoveMenu(@Param("width") int width, @Param("right") Long right);

}