package com.github.wangfeng.iadmin.dao;


import com.github.wangfeng.iadmin.common.po.entity.DemoDO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    int insert(DemoDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    DemoDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    List<DemoDO> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo
     *
     * @mbg.generated Fri Sep 13 14:22:00 CST 2019
     */
    int updateByPrimaryKey(DemoDO record);
}